### Fixed

- Tracking with the AI model was not starting automatically after being re-enabled
  (<https://github.com/cvat-ai/cvat/pull/9376>)
